const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  try {
    const page = await browser.newPage();
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const url = 'file:///C:/Users/user/Documents/ChatGPT/GRID/index.html';
    await page.goto(url);
    await page.locator('[data-language="ru"]').click();
    await page.goto(url + '#card-16');
    const active = '.reading-page.swiper-slide-active';
    await page.locator(active + ' .edit-page').click();
    const body = 'Мой текст про бота.\n\n- Доходы\n- Расходы\n\n<Это просто текст>';
    await page.locator(active + ' .edit-title').fill('Мой Cointry');
    await page.locator(active + ' .edit-body').fill(body);
    await page.keyboard.press('ArrowRight');
    assert.equal(new URL(page.url()).hash, '#card-16');
    await page.reload();
    assert.equal(await page.locator(active + ' h3').textContent(), 'Мой Cointry');
    assert.equal(await page.locator(active + ' .page-list li').count(), 2);
    await page.locator(active + ' .edit-page').click();
    assert.equal(await page.locator(active + ' .edit-body').inputValue(), body);
    await page.locator('#modal-close').click();
    await page.locator('#toggle-catalog-editor').click();
    assert.equal(await page.locator('.catalog-editor-row').count(), 29);
    assert.equal(await page.locator('#gallery').isVisible(), false);
    await page.locator('[data-card-id="card-16"] .catalog-title').fill('Мои боты');
    await page.locator('[data-card-id="card-16"] .catalog-summary').fill('Короткая подпись от меня');
    assert.equal(await page.locator('#card-16 .card-title').textContent(), 'Мои боты');
    assert.equal(await page.locator('#card-16 .subtitle').textContent(), 'Короткая подпись от меня');
    await page.reload();
    await page.locator('#toggle-catalog-editor').click();
    assert.equal(await page.locator('[data-card-id="card-16"] .catalog-title').inputValue(), 'Мои боты');
    await page.locator('#toggle-catalog-editor').click();
    assert.equal(await page.locator('#gallery').isVisible(), true);
    await page.goto(url + '#card-16');
    assert.equal(await page.locator('#modal-title').textContent(), 'Мои боты');
    assert.equal(await page.locator('#modal-description').textContent(), 'Короткая подпись от меня');
    assert.equal(await page.locator(active + ' h3').textContent(), 'Мой Cointry');
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#export-edits').click();
    const download = await downloadPromise, chunks = [];
    for await (const chunk of await download.createReadStream()) chunks.push(chunk);
    const exported = JSON.parse(Buffer.concat(chunks).toString('utf8'));
    assert.equal(exported.edits.length, 2);
    assert.equal(exported.edits.find(edit => edit.type === 'card').title, 'Мои боты');
    assert.equal(exported.edits.find(edit => edit.type === 'card').text, 'Короткая подпись от меня');
    assert.equal(exported.edits[0].cardId, 'card-16');
    assert.equal(exported.edits[0].language, 'ru');
    assert.equal(exported.edits[0].text, body);
    await page.locator('#modal-close').click();
    await page.locator('[data-language="en"]').click();
    await page.goto(url + '#card-16');
    assert.equal(await page.locator('#modal-title').textContent(), 'Telegram bots');
    assert.equal(await page.locator(active + ' h3').textContent(), 'Cointry');
    await page.locator(active + ' .edit-page').click();
    await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Storage unavailable'); }; });
    await page.locator(active + ' .edit-body').fill('English draft');
    assert.match(await page.locator('#draft-status').textContent(), /storage failed/);
    assert.equal(await page.locator('#export-edits').isEnabled(), true);
    assert.deepEqual(errors, []);
    console.log('Drafts: editing, reload persistence, list preview, exact JSON export, language isolation, arrow keys and storage failure handling passed.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
